---

- name: Create download directory
  file: path="{{ rkt_download_dir }}" state=directory mode=0755
  tags: ['rkt', 'rkt:install']

- name: Create rkt install directory
  file: path="{{ rkt_acbuild_install_dir }}" state=directory
  tags: ['rkt', 'rkt:install']

- include: acbuild.yml
  when: rkt_install_acbuild

- name: Download rkt package
  get_url: url="{{ rkt_url }}" dest="{{ rkt_download_dir }}/{{ rkt_filename }}"
  tags: ['rkt', 'rkt:install']

- name: Download rkt signature
  get_url: url="{{ rkt_sig_url }}" dest="{{ rkt_download_dir }}/{{ rkt_sig_filename }}"
  tags: ['rkt', 'rkt:install']

- name: Import rkt signing key
  command: gpg --keyserver {{ rkt_keyserver }} --recv {{ rkt_sig_key }}
  tags: ['rkt', 'rkt:install']

- name: Verify rkt signature
  command: gpg --verify {{ rkt_download_dir }}/{{ rkt_sig_filename }} {{ rkt_download_dir }}/{{ rkt_filename }}
  tags: ['rkt', 'rkt:install']

- name: Install rkt
  apt: deb="{{ rkt_download_dir }}/{{ rkt_filename }}"
  tags: ['rkt', 'rkt:install']

- name: Trust repository keys
  command: >
    rkt trust
    --skip-fingerprint-review
    {{ item.root is defined | ternary('--root ' + item.root | default(omit), '') }}
    {{ item.prefix is defined | ternary('--prefix ' + item.prefix | default(omit), '') }}
    {{ item.location is defined | ternary(item.location | default(omit), '') }}
  with_items: rkt_trust
  tags: ['rkt', 'rkt:configuration']

- name: Fetch rkt images
  command: >
    rkt fetch
    {{ item.signature is defined | ternary('--signature ' + item.signature | default(omit), '') }}
    {{ item.pull_policy is defined | ternary('--pull-policy ' + item.pull_policy | default(omit), '') }}
    {{ item.image }}
  with_items: rkt_fetch_images
  tags: ['rkt', 'rkt:configuration']
