---

- name: Add SSH authorized keys
  authorized_key: >
    user={{ item.user }}
    key={{ item.pubkey }}
  with_items: ssh_pubkeys
  tags: ['ssh', 'ssh:configuration']

- name: Set SSH port
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^Port"
    line="Port {{ ssh_port }}"
    backup=yes
    validate="/usr/sbin/sshd -T -f %s"
  notify: reload ssh
  tags: ['ssh', 'ssh:configuration']

- name: Enable/Disable SSH password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication {{ ssh_password_auth }}"
    backup=yes
    validate="/usr/sbin/sshd -T -f %s"
  notify: reload ssh
  tags: ['ssh', 'ssh:configuration']

- name: Enable/Disable SSH root login
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin {{ ssh_permit_root_login }}"
    backup=yes
    validate="/usr/sbin/sshd -T -f %s"
  notify: reload ssh
  tags: ['ssh', 'ssh:configuration']

- name: Set allowed groups
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^AllowGroups"
    line="AllowGroups {{ ssh_allow_groups }}"
    backup=yes
    validate="/usr/sbin/sshd -T -f %s"
  notify: reload ssh
  when: ssh_allow_groups != ""
  tags: ['ssh', 'ssh:configuration']

- name: Set allowed users
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^AllowUsers"
    line="AllowUsers {{ ssh_allow_users }}"
    backup=yes
    validate="/usr/sbin/sshd -T -f %s"
  notify: reload ssh
  when: ssh_allow_users != ""
  tags: ['ssh', 'ssh:configuration']

- name: Set denied groups
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^DenyGroups"
    line="DenyGroups {{ ssh_deny_groups }}"
    backup=yes
    validate="/usr/sbin/sshd -T -f %s"
  notify: reload ssh
  when: ssh_deny_groups != ""
  tags: ['ssh', 'ssh:configuration']

- name: Set denied users
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^DenyUsers"
    line="DenyUsers {{ ssh_deny_users }}"
    backup=yes
    validate="/usr/sbin/sshd -T -f %s"
  notify: reload ssh
  when: ssh_deny_users != ""
  tags: ['ssh', 'ssh:configuration']

- name: Trigger handler to restart SSH
  command: "/bin/true"
  notify: restart ssh
  when: ssh_restart
  tags: ['ssh', 'ssh:configuration']
